import type { Metadata } from "next";
import "./globals.css";
import { SanityLive } from "@/sanity/lib/live";
import Header from "@/components/Header";
import NextTopLoader from 'nextjs-toploader';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Mozze tech",
  description: "Generated by Mozze tech",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased bg-[#caf0f8]`}
      >
      <Header />
      <NextTopLoader color="#FFFFFF" />
        {children}
        <SanityLive/>
      </body>
    </html>
  );
}
